name: Distribute Dev Release Build to Firebase

on:
  workflow_dispatch:

jobs:

  distributeDefaultDebug:
    name: Distribute Default Debug Version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.x'

      - name: Install bundle
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Create service credentials file
        run: |
          echo "$FIREBASE_CREDENTIALS" > firebase_credentials.json.b64
          base64 -d -i firebase_credentials.json.b64 > AppDistributionConfig/firebase-credentials.json
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.CRYPTO_FIREBASE_CREDENTIALS }}

      - name: Store CLI Token as environment variable
        run: echo "CRYPTO_CLI_TOKEN=${{ secrets.CRYPTO_CLI_TOKEN }}" >> $GITHUB_ENV

      - name: Store Application ID as environment variable
        run: echo "CRYPTO_APP_ID=${{ secrets.CRYPTO_APP_ID }}" >> $GITHUB_ENV

      - name: Code validation
        run: bundle exec fastlane detekt

      - name: Run unit tests
        run: bundle exec fastlane unitTest

      - name: Deploy Default Debug build to Firebase App Distribution
        run: bundle exec fastlane deployToFirebase